Commiting recent changes to ask for guidence. When running tests, a TypeError is thrown (in testLegoPileInsert.js, line 22) that says ...insertBrickByColor is not a function, but the console message jsut above i use for debugging purposes clearly shows it is a function.